#!/bin/sh

echo "========================================================"
echo "Creating your private key"
echo "========================================================"

mkdir ~/.testaws/
mkdir -p ~/.testaws/certs
openssl genrsa 1024 > ~/.testaws/certs/pk.pem
openssl req -new -x509 -nodes -sha1 -days 3650 -key ~/.testaws/certs/pk.pem -outform PEM > ~/.testaws/certs/cert.pem

echo "========================================================"
echo "Downloading the ec2 tools"
echo "========================================================"

cd ~/.testaws/
curl --output ./ec2.zip http://s3.amazonaws.com/ec2-downloads/ec2-ami-tools.zip
unzip ec2.zip
rm ec2.zip

echo "========================================================"
echo "Log into the AWS console and from the drop down menu under your email address, select Security Credentials. From the left, select Users then select your account name."
echo "In the bottom panel, click Manage Access Keys -> Create Key. Note the AWS Key ID and the AWS Secret Key as they will be needed shortly."
echo "In the same bottom panel, select Manage Signing Certificates -> Upload Signing Certificate"
echo "Paste this certificate text into the box:"

cat ~/.testaws/certs/cert.pem
source $HOME/.bash_profile

echo "========================================================"
echo "AWS should now be all set up :)"
echo "========================================================"
