#!/bin/sh
#
# bootstrap installs things.

# Ask for the administrator password upfront
sudo -v

echo "========================================================"
echo "Installing some core software using Homebrew"
echo "========================================================"

if [ $(uname -s) = "Darwin" ] 
then
  . script/homebrew
fi

echo "========================================================"
echo "Copying exports into bash_profile"
echo "Making aliases global"
echo "========================================================"

cat script/snippet.SOURCE >> $HOME/.bash_profile
source $HOME/.bash_profile

echo "========================================================"
echo "Reconfiguring OSX Defaults"
echo "========================================================"

source osx/set-defaults.sh

echo "========================================================"
echo "Symlinking config files"
echo "========================================================"

rake install

echo "========================================================"
echo "AWS Set up"
echo "========================================================"

source script/aws